### ISSUE TITLE
Poor performance for large data structures

### ISSUE THREAD

**Issue by mvindahl** [webpolis/angular-treecursive#10]
Hi,

In our project, we are occasionally faced with having to render trees based upon very large data structures. It's an implicit requirement that these do not drag down the UI. I've experimented a bit with treecursive and large generated data sets, and above a couple thousand items the performance begins to degrade noticely (on a pretty fast MacBook). Above about 10K items it seems to kill the browser.

I have a fix, though. Replacing the ng-show="!node.collapsed" in the code by a ng-if="!node.collapsed" will cause the tree to build itself lazily instead of building itself initially and then hiding collapsed branches. This will only work if nodes are initially collapsed, i.e. for an initially expanded tree it would not be expected to make any positive difference.

I've forked the repository and expect to make the change in a non-obtrusive manner, i.e. it will use ng-show as default and ng-if if you actively specify so in an attribute. Having done so, I'd be happy to make a pull request, if you are interested.

**Comment by webpolis** [comment]
Feel free to do a PR.

Btw, as a comment apart, loading 10K items in the DOM it's always not a good idea. I don't know the specific reasons why your team do that, I guess you may have legitimate reasons.

Apart from my thoughts, you're comments still are correct. Please let me check further.

Thanks

**Comment by mvindahl** [comment]
Thanks, I'll submit a PR shortly.

On a side note, I agree that loading 10K items into the DOM is not a healthy thing to do, and it's also a bit of a border case that we have that kind of data. Most data structures will be be much more manageable but we need to be able to handle the outliers as well. As it turns out, 10K items is not a bit problem to hold in memory but it takes a long time to render to the DOM, so the point is more or less to prevent it whole thing from being rendered ...

**Comment by webpolis** [comment]
Thanks @mvindahl
