### ISSUE TITLE
Mouse events fire twice

### ISSUE THREAD

**Issue by mvindahl** [webpolis/angular-treecursive#12]
I've only tested the following with ng-click but I suspect that the bug would extend to wide range of event types. In any case, if I define an event listener upon a child element of the treecursive directive, the listener will fire twice. The only exception is for ng-click on the topmost element, due to a patch in the code (`angular.element(clone[1]).attr('ng-click', false);` in the clone function).

The problem seems to be that the elements are compiled twice; both when they are created and when a treecursive element has been added to expand to a child list. As a result, event listeners are registerd twice.

As far as I can tell, it's just a matter of compiling the nested treecursive element without recompiling the stuff which was already compiled. I.e. replace
`$compile($element.contents())($scope);`
by
`$compile(sub[0])($scope);`
and everything appears to work. The ng-click patch can then be removed.

If you'd like a PR then I can create easily create one, but it's just a couple of lines.

**Comment by webpolis** [comment]
@mvindahl  feel free to submit pull requests and I'll merge. Make yourself a contributor :)

**Comment by webpolis** [comment]
@mvindahl It seems this has been already implemented in your previous PR https://github.com/webpolis/angular-treecursive/blob/master/angular-treecursive.js#L40 ... right? Please confirm.
