### ISSUE TITLE
Please release bower version with support for children attr

### ISSUE THREAD

**Issue by mvindahl** [webpolis/angular-treecursive#9]
Hi,

We've decided to depend upon your tree control for our project. It's simple, it's flexible, it's angular style, and it does exactly what it says on the tin, no bloat attached :)

However, due to the structure of our data, we need to make use of the "children" attribute. This is on the master but it's currently not included in the bower release. Our current workaround is to link directly to a github project SHA ("angular-treecursive": "https://github.com/webpolis/angular-treecursive.git#21186ec728847b6a8385d9330295e938d01909ef" in bower.json) but we'd prefer to be able to refer to the dependency in a more standard bower manner.

Thanks in advance,
/Martin

**Comment by webpolis** [comment]
Hi Martin

Thanks for the feedback. I'm glad you find this component useful. Please give me couple of hours to review your inquiries and will provide you a solution for sure.

Regards,
Nicolás

**Comment by mvindahl** [comment]
I think it's as simple as bumping the version to 1.1.2 in bower.json and tagging the commit with the same semver. Then bower should pick it up automatically. At least that's my experience.
